#!/usr/bin/env python3
"""Generate an idempotent SQL migration for the curated PTcert FAQ corpus."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
CONTENT = ROOT / "db" / "ptcert-content"


def escape(value: str) -> str:
    return value.replace("\\", "\\\\").replace("'", "''")


def quoted(value: str) -> str:
    return "'" + escape(value) + "'"


def category_sql(name: str, comment: str, parent_variable: str, variable: str) -> list[str]:
    return [
        f"INSERT INTO faq_category (parent_id, name, comments, valid_id, created, created_by, changed, changed_by)",
        f"SELECT {parent_variable}, {quoted(name)}, {quoted(comment)}, 1, UTC_TIMESTAMP(), 2, UTC_TIMESTAMP(), 2",
        f"FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM faq_category WHERE parent_id = {parent_variable} AND name = {quoted(name)});",
        f"SET {variable} = (SELECT id FROM faq_category WHERE parent_id = {parent_variable} AND name = {quoted(name)} ORDER BY id LIMIT 1);",
        f"INSERT INTO faq_category_group (category_id, group_id, created, created_by, changed, changed_by)",
        f"SELECT {variable}, g.id, UTC_TIMESTAMP(), 2, UTC_TIMESTAMP(), 2 FROM groups_table g",
        f"WHERE g.name IN ('bwb_helpdesk_manual_editors','bwb_helpdesk_manual_readers')",
        f"AND NOT EXISTS (SELECT 1 FROM faq_category_group cg WHERE cg.category_id = {variable} AND cg.group_id = g.id);",
        "",
    ]


def build_sql(content_dir: Path) -> str:
    manifest = json.loads((content_dir / "manifest.json").read_text(encoding="utf-8"))
    lines = [
        "-- PTcert internal knowledge base.",
        "-- Idempotent by category parent/name and article f_number.",
        "-- Generated by scripts/apply-ptcert-faq.py; do not edit generated SQL by hand.",
        "SET NAMES utf8mb4;",
        "SET autocommit = 0;",
        "START TRANSACTION;",
        "SET @internal_id = (SELECT id FROM faq_category WHERE parent_id = 0 AND name = 'Documentação interna' ORDER BY id LIMIT 1);",
        "SET @assert_sql = IF(@internal_id IS NULL, \"SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Categoria Documentação interna não encontrada'\", 'DO 0');",
        "PREPARE assert_stmt FROM @assert_sql;",
        "EXECUTE assert_stmt;",
        "DEALLOCATE PREPARE assert_stmt;",
        "",
    ]
    lines.extend(category_sql("PTcert", "Base de conhecimento interna do PTcert para agentes de suporte.", "@internal_id", "@ptcert_id"))
    for slug, (name, comment) in manifest["categories"].items():
        lines.extend(category_sql(name, comment, "@ptcert_id", f"@cat_{slug}"))

    for article in manifest["articles"]:
        body = (content_dir / article["body"]).read_text(encoding="utf-8").strip()
        category_var = f"@cat_{article['category']}"
        values = {
            "number": quoted(article["number"]),
            "name": quoted(article["name"]),
            "title": quoted(article["title"]),
            "keywords": quoted(article["keywords"]),
            "summary": quoted(article["summary"]),
            "use_when": quoted(article["use_when"]),
            "body": quoted(body),
        }
        lines.extend([
            f"-- {article['number']} — {article['title']}",
            "INSERT INTO faq_item (f_number, f_name, f_subject, f_language_id, state_id, category_id, approved, valid_id, content_type, f_keywords, f_field1, f_field2, f_field3, f_field6, created, created_by, changed, changed_by)",
            f"SELECT {values['number']}, {values['name']}, {values['title']}, 3, 2, {category_var}, 1, 1, 'text/html', {values['keywords']}, {values['summary']}, {values['use_when']}, {values['body']}, '', UTC_TIMESTAMP(), 2, UTC_TIMESTAMP(), 2",
            f"FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM faq_item WHERE f_number = {values['number']});",
            "UPDATE faq_item SET",
            f"  f_name={values['name']}, f_subject={values['title']}, f_language_id=3, state_id=2, category_id={category_var},",
            f"  approved=1, valid_id=1, content_type='text/html', f_keywords={values['keywords']},",
            f"  f_field1={values['summary']}, f_field2={values['use_when']}, f_field3={values['body']}, f_field6='',",
            "  changed=UTC_TIMESTAMP(), changed_by=2",
            f"WHERE f_number={values['number']};",
            f"SET @faq_id = (SELECT id FROM faq_item WHERE f_number={values['number']} ORDER BY id LIMIT 1);",
            f"DELETE FROM faq_attachment WHERE faq_id=@faq_id AND filename LIKE {quoted('PTCERT-' + article['name'] + '-%')};",
        ])
        for asset in article["assets"]:
            asset_path = content_dir / asset["path"]
            binary_hex = asset_path.read_bytes().hex()
            content_type = f"{asset['content_type']}; name=\"{asset['filename']}\""
            lines.extend([
                "INSERT INTO faq_attachment (faq_id, filename, content_size, content_type, content, inlineattachment, created, created_by, changed, changed_by)",
                f"VALUES (@faq_id, {quoted(asset['filename'])}, {quoted(str(asset_path.stat().st_size))}, {quoted(content_type)}, UNHEX('{binary_hex}'), 1, UTC_TIMESTAMP(), 2, UTC_TIMESTAMP(), 2);",
                "SET @file_id = LAST_INSERT_ID();",
                f"UPDATE faq_item SET f_field3=REPLACE(f_field3, {quoted(asset['token'])}, CONCAT('/otobo/index.pl?Action=AgentFAQZoom;Subaction=DownloadAttachment;ItemID=', @faq_id, ';FileID=', @file_id)) WHERE id=@faq_id;",
            ])
        lines.append("")
    lines.extend(["COMMIT;", ""])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--content", type=Path, default=CONTENT)
    parser.add_argument("--write", type=Path, required=True)
    args = parser.parse_args()
    sql = build_sql(args.content)
    args.write.parent.mkdir(parents=True, exist_ok=True)
    args.write.write_text(sql, encoding="utf-8")
    print(f"{args.write} ({args.write.stat().st_size} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
